sudo:
  false

language:
  php

php:
  - 5.6
  - 7
  - hhvm

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist --colors --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls